theme = "monokai_pro_ristretto"

[editor]
line-number = "relative"
scrolloff = 8
mouse = true
bufferline = "multiple"
color-modes = true

[editor.statusline]
right = ["diagnostics", "file-type", "register", "file-encoding"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw", ":rla"]
