[[language]]
name = "markdown"
formatter = { command = "dprint", args = ["fmt", "--stdin", "md"] }
auto-format = true

[[language]]
name = "latex"
formatter = { command = "tex-fmt", args = ["--stdin"]}
auto-format = true
